version: "2"
services:
  web:
    build: ./web
    ports:
      - "513:3000"
    links:
      - iot-gateway

  iot-gateway:
    build: ./iot-gateway
    ports:
      - "512:8080"
    networks:
      - redis_net
    depends_on:
      - redis

  redis:
    image: redis:5.0.6-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis_net
    volumes:
      - redis_data:/data

volumes:
  redis_data: {}
networks:
  redis_net: