version: "2"
services:
  web:
    build: ./web
    links:
      - iot-gateway
    networks:
      - local_net

  iot-gateway:
    build: ./iot-gateway
    ports:
      - "5120:8080"
    networks:
      - local_net
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - redis

  redis:
    image: redis:5.0.6-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - local_net
    volumes:
      - redis_data:/data

volumes:
  redis_data: {}
networks:
  local_net: