version: "2"
services:
  iot-gateway:
    build: ./iot-gateway
    ports:
      - "512:8080"
    links:
      - redis

  redis:
    image: redis:5.0.6-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "7379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: {}